import 'ai_flow_manifest.dart';
import 'ai_nav_entry.dart';
import 'ai_screen_manifest.dart';

/// Complete hierarchical description of the app for AI navigation.
///
/// This is the "building map" the agent reads before exploring. It provides
/// rich context about every screen, their relationships, and multi-screen
/// flows — allowing the agent to plan tasks without visiting screens first.
///
/// Generated by `dart run flutter_ai_assistant:generate` and optionally
/// edited by the developer.
class AiAppManifest {
  /// Human-readable name of the app.
  final String appName;

  /// One-paragraph description of what this app does, written for an LLM.
  final String appDescription;

  /// All screens in the app, keyed by route name (e.g., "/wallet").
  final Map<String, AiScreenManifest> screens;

  /// Multi-step user journeys that span multiple screens.
  final List<AiFlowManifest> flows;

  /// Global navigation structure (e.g., bottom nav tabs, side menu items).
  final List<AiNavEntry> globalNavigation;

  const AiAppManifest({
    required this.appName,
    required this.appDescription,
    required this.screens,
    this.flows = const [],
    this.globalNavigation = const [],
  });

  /// Get the manifest for a specific screen, or null if not found.
  AiScreenManifest? screenFor(String route) => screens[route];

  /// Format the full app map as an LLM-readable prompt section (Tier 1).
  ///
  /// This produces the high-level overview of all screens that is always
  /// included in the system prompt.
  String toAppMapPrompt() {
    final buffer = StringBuffer();

    // App overview.
    buffer.writeln('APP OVERVIEW:');
    buffer.writeln(appDescription);
    buffer.writeln();

    // Global navigation.
    if (globalNavigation.isNotEmpty) {
      buffer.writeln('GLOBAL NAVIGATION:');
      final navItems = globalNavigation
          .map((n) => '${n.label} (${n.route})')
          .join(', ');
      buffer.writeln('  $navItems');
      buffer.writeln();
    }

    // Screen map.
    buffer.writeln(
      'APP SCREENS (navigate with exact route name including "/"):',
    );
    for (final screen in screens.values) {
      buffer.writeln(
        '  ${screen.route} — ${screen.title} — ${screen.description}',
      );
      if (screen.linksTo.isNotEmpty) {
        final links = screen.linksTo
            .map((l) => '${l.targetRoute} (${l.trigger})')
            .join(', ');
        buffer.writeln('    Links to: $links');
      }
    }
    buffer.writeln();

    // Flows.
    if (flows.isNotEmpty) {
      buffer.writeln('COMMON TASKS (multi-step flows):');
      for (int i = 0; i < flows.length; i++) {
        final flow = flows[i];
        final steps = flow.steps
            .map((s) => '${s.route}: ${s.instruction}')
            .join(' -> ');
        buffer.writeln('  ${i + 1}. ${flow.name}: $steps');
      }
      buffer.writeln();
    }

    return buffer.toString().trimRight();
  }

  /// Format the current screen's manifest detail (Tier 2).
  ///
  /// Returns null if [route] is not in the manifest.
  String? toScreenDetailPrompt(String route) {
    final screen = screens[route];
    if (screen == null) return null;

    final buffer = StringBuffer();
    buffer.writeln('SCREEN KNOWLEDGE (from app manifest):');
    buffer.writeln('  Title: ${screen.title}');
    buffer.writeln('  Description: ${screen.description}');

    if (screen.sections.isNotEmpty) {
      buffer.writeln('  Sections:');
      for (final section in screen.sections) {
        buffer.writeln('    — ${section.title}: ${section.description}');
        for (final elem in section.elements) {
          final behavior = elem.behaviorDescription != null
              ? ' -> ${elem.behaviorDescription}'
              : '';
          buffer.writeln('      [${elem.type}] "${elem.label}"$behavior');
        }
      }
    }

    if (screen.actions.isNotEmpty) {
      buffer.writeln('  Available Actions:');
      for (final action in screen.actions) {
        final destructive = action.isDestructive ? ' [DESTRUCTIVE]' : '';
        buffer.writeln('    — ${action.name}: ${action.howTo}$destructive');
      }
    }

    if (screen.notes.isNotEmpty) {
      buffer.writeln('  Notes: ${screen.notes.join('; ')}');
    }

    return buffer.toString().trimRight();
  }
}
