import 'package:flutter/widgets.dart';

import '../llm/llm_provider.dart';
import '../llm/react_agent.dart';
import '../manifest/ai_app_manifest.dart';
import '../models/chat_content.dart';
import '../tools/tool_definition.dart';
import 'ai_event.dart';

/// A suggestion chip shown in the chat overlay's empty state.
///
/// Developers configure these to provide quick-start actions relevant to
/// their app's domain (e.g., "Book a ride", "Browse store", "Check balance").
class AiSuggestionChip {
  /// Icon displayed before the label.
  final IconData icon;

  /// Short label shown on the chip.
  final String label;

  /// Message sent to the assistant when the chip is tapped.
  final String message;

  const AiSuggestionChip({
    required this.icon,
    required this.label,
    required this.message,
  });
}

/// Callback type for building post-task follow-up chips.
///
/// Receives the agent's response (including actions performed) and returns
/// a [ButtonsContent] with relevant follow-up suggestions, or null if no
/// suggestions are appropriate.
typedef PostTaskChipsBuilder = ButtonsContent? Function(AgentResponse response);

/// Configuration for the AI Assistant.
class AiAssistantConfig {
  /// Required: the LLM provider to use for processing commands.
  final LlmProvider provider;

  /// Whether voice input/output is enabled. Default: true.
  final bool voiceEnabled;

  /// Whether to show the floating action button. Default: true.
  final bool showFloatingButton;

  /// Optional developer-registered custom tools (business logic actions).
  final List<AiTool> customTools;

  /// Optional: list of all named routes in the app.
  /// If not provided, routes are discovered progressively via NavigatorObserver.
  final List<String> knownRoutes;

  /// Optional: human-readable descriptions for routes.
  /// Helps the LLM understand what each screen does.
  final Map<String, String> routeDescriptions;

  /// Optional: callback that provides app-level state (user info, cart, etc.).
  /// Called when building context for the LLM.
  final Future<Map<String, dynamic>> Function()? globalContextProvider;

  /// Optional: custom navigation callback. If not provided, the library
  /// attempts to navigate using the NavigatorState from the widget tree.
  final Future<void> Function(String routeName)? navigateToRoute;

  /// Whether destructive actions (purchases, deletions) require user
  /// confirmation before execution. Default: true.
  final bool confirmDestructiveActions;

  /// Maximum number of reason-act-observe iterations per user message.
  /// Prevents infinite loops. Default: 30.
  final int maxAgentIterations;

  /// Maximum number of post-completion verification passes. Default: 2.
  ///
  /// After the agent returns a text response following actions, the system
  /// re-checks the screen to verify the task is genuinely complete.
  /// For simple tasks the first pass confirms and returns immediately.
  /// For multi-step flows a second pass catches premature completion.
  final int maxVerificationAttempts;

  /// How long to cache a screen's semantics snapshot before re-capturing.
  /// Default: 10 seconds.
  final Duration contextCacheTtl;

  /// Optional: override the entire system prompt sent to the LLM.
  final String? systemPromptOverride;

  /// Display name for the assistant. Default: "AI Assistant".
  final String assistantName;

  /// Whether to enable extensive debug logging. Default: false.
  ///
  /// When enabled, logs are written via `dart:developer` and appear in
  /// DevTools. They are automatically stripped from release builds.
  final bool enableLogging;

  /// Optional: rich hierarchical description of the entire app.
  ///
  /// Generated by `dart run flutter_ai_assistant:generate` and optionally
  /// edited by the developer. When provided, the agent uses this as a
  /// detailed "map" of all screens instead of relying solely on route names
  /// and descriptions.
  final AiAppManifest? appManifest;

  /// Optional: a concise description of what this app does, written for an LLM.
  ///
  /// Unlike [AiAppManifest.appDescription] which lists screens, this describes
  /// the app's PURPOSE and domain vocabulary so the agent understands user
  /// intent without asking unnecessary questions.
  ///
  /// Example: "TaskApp is a project management app. Users create tasks,
  /// assign team members, and track deadlines. 'new task'/'create' = create,
  /// 'assign' = assign member, 'done'/'complete' = mark complete."
  final String? appPurpose;

  /// Optional: few-shot examples of correct agent behavior.
  ///
  /// Each string is a complete example block showing User → Plan → Actions →
  /// Response. When provided, these replace the generic built-in examples in
  /// the system prompt, giving the LLM app-specific demonstrations.
  ///
  /// Example:
  /// ```dart
  /// fewShotExamples: [
  ///   'User: "create a new task"\n'
  ///   'Plan: Navigate to tasks → tap create → fill form\n'
  ///   'Actions: navigate_to_route("/tasks") → tap_element("Create") → '
  ///   'set_text("Title", "New task")\n'
  ///   'Response: "Done! Task created."',
  /// ],
  /// ```
  final List<String> fewShotExamples;

  /// Whether to capture screenshots and send them to the LLM for visual
  /// understanding. When enabled, a screenshot is captured after each
  /// screen change and sent alongside the semantics-based context.
  ///
  /// This helps the LLM understand text in images, charts, visual layouts,
  /// and other content that the semantics tree cannot capture.
  ///
  /// Increases API payload by ~100-200KB per iteration. Default: false.
  final bool enableScreenshots;

  /// Extra bottom padding for the floating action button, in logical pixels.
  ///
  /// Use this to push the FAB above your app's bottom navigation bar or
  /// any other persistent bottom UI. Default: 72 (clears a standard
  /// 56px BottomNavigationBar + 16px spacing).
  final double fabBottomPadding;

  /// Preferred speech recognition locales in priority order.
  ///
  /// The first available locale on the device will be used. Hindi (`hi_IN`)
  /// is listed first because Google's speech recognizer handles Hinglish
  /// naturally in this locale.
  ///
  /// Default: `['hi_IN', 'en_IN', 'en_US']`.
  final List<String> preferredLocales;

  /// Whether the agent speaks responses and progress aloud via TTS.
  ///
  /// When disabled, all text-to-speech output is suppressed — the agent
  /// still listens (if [voiceEnabled] is true) but never speaks back.
  /// Default: true.
  final bool enableTts;

  /// Whether haptic feedback is enabled during voice interactions.
  ///
  /// When enabled, the device vibrates on mic activation, speech capture,
  /// action progress ticks, and task completion. Default: true.
  final bool enableHaptics;

  /// Whether the floating action button can be dragged to reposition.
  ///
  /// When enabled, the user can drag the FAB to any vertical position along
  /// either screen edge. The FAB snaps to the nearest horizontal edge on
  /// release with a spring animation. Default: true.
  final bool fabDraggable;

  /// Whether the overlay auto-closes after task completion and shows a
  /// compact response popup above the FAB. Default: true.
  ///
  /// When enabled:
  /// - ACTION tasks (tap, navigate, etc.) → overlay closes, brief popup auto-dismisses
  /// - INFO tasks (balance, details) → overlay closes, response card stays until dismissed
  /// - ERROR tasks → overlay stays open for retry
  ///
  /// When disabled, the overlay always stays open after task completion.
  final bool autoCloseOnComplete;

  /// Domain-specific behavioral instructions injected into the system prompt.
  ///
  /// Use this to teach the agent about your app's specific workflows, terminology,
  /// and expected behaviors. This is the primary extension point for customizing
  /// agent behavior without modifying the package.
  ///
  /// Example for an e-commerce app:
  /// ```dart
  /// domainInstructions: '''
  /// QUANTITIES: When the user specifies a quantity (e.g. "5 onion"),
  /// tap the product name to open its detail page, then use increase_value
  /// to set the desired quantity before adding to cart.
  ///
  /// "order X" means COMPLETE THE FULL PURCHASE:
  /// add to cart → go to cart → checkout → confirm/hand off.
  /// Do NOT stop at "added to cart" — that is an intermediate step.
  /// ''',
  /// ```
  final String? domainInstructions;

  /// Suggestion chips shown in the chat overlay's empty state.
  ///
  /// These provide quick-start actions relevant to your app's domain.
  /// When empty, the empty state shows only the generic prompt text
  /// without any suggestion chips.
  ///
  /// Example:
  /// ```dart
  /// initialSuggestions: [
  ///   AiSuggestionChip(
  ///     icon: Icons.directions_car,
  ///     label: 'Book a ride',
  ///     message: 'Book me a ride',
  ///   ),
  ///   AiSuggestionChip(
  ///     icon: Icons.storefront,
  ///     label: 'Browse store',
  ///     message: 'Take me to the store',
  ///   ),
  /// ],
  /// ```
  final List<AiSuggestionChip> initialSuggestions;

  /// Optional callback to build post-task follow-up suggestion chips.
  ///
  /// Called after the agent completes a task. Receives the agent's response
  /// (including all actions performed) and returns a [ButtonsContent] with
  /// relevant follow-up suggestions, or null if no suggestions are appropriate.
  ///
  /// Example:
  /// ```dart
  /// postTaskChipsBuilder: (response) {
  ///   final addedToCart = response.actions.any((a) =>
  ///       a.toolName == 'tap_element' &&
  ///       (a.arguments['label'] as String?)?.toLowerCase().contains('add') == true);
  ///   if (addedToCart) {
  ///     return ButtonsContent(buttons: [ChatButton(label: 'View my cart')]);
  ///   }
  ///   return null;
  /// },
  /// ```
  final PostTaskChipsBuilder? postTaskChipsBuilder;

  /// Optional callback for receiving structured analytics events.
  ///
  /// Called for every significant event in the assistant lifecycle —
  /// conversation start/end, each agent iteration, every tool call,
  /// LLM requests/responses, voice I/O, UI interactions, errors, etc.
  ///
  /// Use this to pipe events into your analytics platform (Firebase,
  /// Mixpanel, custom backend) or for debugging and monitoring.
  ///
  /// Example:
  /// ```dart
  /// onEvent: (event) {
  ///   FirebaseAnalytics.instance.logEvent(
  ///     name: 'ai_${event.type.name}',
  ///     parameters: event.properties.map(
  ///       (k, v) => MapEntry(k, v?.toString() ?? ''),
  ///     ),
  ///   );
  /// },
  /// ```
  final AiEventCallback? onEvent;

  const AiAssistantConfig({
    required this.provider,
    this.voiceEnabled = true,
    this.showFloatingButton = true,
    this.customTools = const [],
    this.knownRoutes = const [],
    this.routeDescriptions = const {},
    this.globalContextProvider,
    this.navigateToRoute,
    this.confirmDestructiveActions = true,
    this.maxAgentIterations = 30,
    this.contextCacheTtl = const Duration(seconds: 10),
    this.systemPromptOverride,
    this.assistantName = 'AI Assistant',
    this.enableLogging = false,
    this.appManifest,
    this.appPurpose,
    this.fewShotExamples = const [],
    this.enableScreenshots = false,
    this.preferredLocales = const ['hi_IN', 'en_IN', 'en_US'],
    this.enableTts = true,
    this.enableHaptics = true,
    this.fabBottomPadding = 72,
    this.fabDraggable = true,
    this.maxVerificationAttempts = 2,
    this.autoCloseOnComplete = true,
    this.domainInstructions,
    this.initialSuggestions = const [],
    this.postTaskChipsBuilder,
    this.onEvent,
  });
}
